### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gcormier** [vekexasia/mysqldumpsplit#3]
Getting this error when I run it on a 3gb file.

```
Starting :)
{ Error: EINVAL: invalid argument, read errno: -4071, code: 'EINVAL', syscall: 'read' }
```

File was produced with
`mysqldump --user xxx --password=yyy --host zzz mydatabase --compress=TRUE --add-drop-table --add-drop-trigger --add-locks -r mybackup.sql
`

**Comment by vekexasia** [comment]
Hmm @gcormier can you try to see if splitting the file in half gives the same problem in, at least, one of the 2 split?

take a look here for how ot split: http://www.howtogeek.com/howto/ubuntu/split-a-text-file-in-half-or-any-percentage-on-ubuntu-linux/

If one of the two only gives the problem, try to split it again in half so that you cna pinpoint the issue on a small file that you could also send to me via email (so that i can provide a bugfix)

**Comment by gcormier** [comment]
Sure, I'll try to take a look over the weekend and report back! One point is the error happens instantly after running the command.. there's no delay.. then it sits for a bit (15 seconds?), then the process ends.

**Comment by konstantinkrassmann** [comment]
Same issue here, when trying to use it in the CLI. 
It just instantly shows this message. Windows10

**Comment by vekexasia** [comment]
@gcormier & @konstantinkrassmann both generated with --compress=TRUE ?

**Comment by konstantinkrassmann** [comment]
No, i didnt use the compress flag on my backup.

**Comment by vekexasia** [comment]
@konstantinkrassmann how big is your file? Can you try with a smaller one?

**Comment by konstantinkrassmann** [comment]
The size of the file is 8 GB, containing 1 table with 6 gb of data.
I did try with a 100 mb file, same error message. The only noticeable difference was, that the script terminated faster. With the big file, it took like 10-15 seconds until the script stopped.

Windows 10, node 4.6.1
